### ISSUE TITLE
Current DateTime Issue

### ISSUE THREAD

**Issue by Spraynard** [icamys/php-sitemap-generator#3] opened 2018-05-08 14:42 UTC
So I see in your example, you have a call to `->addUrl` like this

`$generator->addUrl('http://example.com/url/path/', date('c'), 'always', '0.5');`

but when I use `date('c')` as a the lastmodified date I keep on getting a 

```
Argument 2 passed to Icamys\SitemapGenerator\SitemapGenerator::addUrl() must be an instance of DateTime, string given
```

This is because `date('c')` resolves to a string. It took me quite a while to realize this and I feel like it shouldn't be displayed like that in the example.

**Comment by Spraynard** [comment] 2018-05-08 14:49
Also, it looks like, in your code, for the lastmodified option, you are doing this operation
```
$lastModified->format(\DateTime::ISO8601);
```
I keep on getting errors from google search console saying that this is not a valid date format. I searched on PHP.net and this is what I found
![php net_datetime](https://user-images.githubusercontent.com/17299952/39764391-86a00c56-52ad-11e8-81ad-b20aa2414106.png)

**Comment by icamys** [comment] 2019-06-02 13:54
@Spraynard Thank you for the report. The issue is fixed now.

**Closed** 2019-06-02 13:54 UTC
